[package]
authors = ["Dock.io", "Tobias Looker <tobias.looker@mattr.global>", "Mike Lodder <redmike7@gmail.com>"]
description = "WASM binding to Dock's crypto lib"
edition = "2018"
license = "Apache-2.0"
name = "wasm"
repository = "https://github.com/docknetwork/crypto-wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
console = ["console_error_panic_hook"]
default = ["wee_alloc"]

[dependencies]
console_error_panic_hook = { version = "0.1.1", optional = true }
js-sys = "0.3"
rand = { version = "0.7", features = ["wasm-bindgen"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
serde-wasm-bindgen = "0.3.1"
wasm-bindgen = "= 0.2.74"
wasm-bindgen-futures = "0.4.18"
web-sys = { version = "0.3.39", features = ['console'] }
wee_alloc = { version = "0.4.5", optional = true }
bbs_plus = { version = "0.5.0", default-features = false }
vb_accumulator = { version = "0.4.3", default-features = false }
schnorr_pok = { version = "0.4.1", default-features = false }
proof_system = { version = "0.5.3", default-features = false }
dock_crypto_utils = { version = "0.2.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-ff = { version = "^0.3.0", default-features = false }
ark-bls12-381 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
ark-serialize = { version = "^0.3.0", default-features = false, features = [ "derive" ] }
blake2 = { version = "0.9", default-features = false }
getrandom = { version = "0.2", features = ["js"] }
ark-std = { version = "^0.3.0", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
lto = true
opt-level = "s"
